# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ac酱のSecret Base
brief-intro: Talk is cheap!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://changwh.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username: 
github_username:  changwh
email: 
weibo_username: 
zhihu_username: 
linkedIn_username: 
dribbble_username:

description_footer: 记录搬砖生活中的点滴收获!

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: #changwh
# 由于duoshuo停止服务，disqus需要番羽土啬，畅言需要备案，不适合github page使用，因此选择gitment
#gitment
comment_gitment_repo: changwh.github.io
comment_gitment_clientId: 052c6f0d7676266449da
comment_gitment_clientSecret: 3cc99ac1e91d233616444e31760085ea3f905d71

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 1b2184a20619ac6101ff74463752a337
google_analytics_id: #UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6

# to solve skipping:XXXX.md had a future date
# future: true  ---wrong
timezone: Asia/Shanghai